/* ============================================================
   Anas Tour — shared tour data
   Used by both index.html (featured) and tours.html (full list)
   ============================================================ */
window.ANAS_TELEGRAM = "https://t.me/ANASTOUR_uz";

window.ANAS_TOURS = [
  {
    id: 1,
    title: "Umra Ziyorati — Makka & Madina",
    region: "Umra",
    category: "umra",
    duration: "12 kun",
    price: "$1 450",
    badge: "Ommabop",
    image: "images/umra.png",
    featured: true,
  },
  {
    id: 2,
    title: "Istanbul Klassik Turi",
    region: "Osiyo",
    category: "osiyo",
    duration: "6 kun",
    price: "$690",
    badge: "Chegirma",
    badgeType: "sale",
    image: "images/asia.png",
    featured: true,
  },
  {
    id: 3,
    title: "Parij — Romantik Yevropa",
    region: "Yevropa",
    category: "yevropa",
    duration: "7 kun",
    price: "$1 190",
    badge: "Ommabop",
    image: "images/europe.png",
    featured: true,
  },
  {
    id: 4,
    title: "Maldiv Orollari — Lyuks Dam",
    region: "Plyaj",
    category: "plyaj",
    duration: "8 kun",
    price: "$1 980",
    badge: "Premium",
    image: "images/beach.png",
    featured: true,
  },
  {
    id: 5,
    title: "Dubay — Zamonaviy Sharq",
    region: "Osiyo",
    category: "osiyo",
    duration: "5 kun",
    price: "$850",
    badge: "Chegirma",
    badgeType: "sale",
    image: "images/dubai.png",
  },
  {
    id: 6,
    title: "Shveytsariya Alp Tog'lari",
    region: "Yevropa",
    category: "yevropa",
    duration: "9 kun",
    price: "$1 640",
    badge: "Premium",
    image: "images/swiss.png",
  },
  {
    id: 7,
    title: "Madina Ziyorat Paketi",
    region: "Umra",
    category: "umra",
    duration: "10 kun",
    price: "$1 280",
    badge: "Ommabop",
    image: "images/madina.png",
  },
  {
    id: 8,
    title: "Antalya Dengiz Bo'yi",
    region: "Plyaj",
    category: "plyaj",
    duration: "7 kun",
    price: "$740",
    badge: "Chegirma",
    badgeType: "sale",
    image: "images/antalya.png",
  },
  {
    id: 9,
    title: "Bali — Tropik Jannat",
    region: "Osiyo",
    category: "osiyo",
    duration: "10 kun",
    price: "$1 520",
    badge: "Premium",
    image: "images/bali.png",
  },
  {
    id: 10,
    title: "Rim — Antik Italiya",
    region: "Yevropa",
    category: "yevropa",
    duration: "6 kun",
    price: "$1 090",
    badge: "Ommabop",
    image: "images/rome.png",
  },
];
